### PR TITLE
Add commit on push and build

### PR DESCRIPTION
**Pull request by ResidentMario**
`push` and `build` now accept an optional `message` `kwarg`.

On `push` and `build`, this `kwarg` will be inserted into the package metadata as a `commit_message: message` key-value pair. If no message is specified, `message` will be `None`.

### CODE REVIEW

**Comment by akarve** [comment]
can you merge latest master? it should fix CI.
also, unit test recommended.

**Comment by ResidentMario** [comment]
Merge done. I can add a unit test, it's a bit of an internal do-nothing field for the moment though.

**Comment by akarve** [comment]
generally, all PRs have unit tests unless there is a specific reason (like a docs change)

**Comment by akarve** [comment]
I think this is a bug:
```
with open("./myman.json", "w") as file:
    p.dump(file)
```
`myman.json` shows `"commit_message": null`

also: can we just call it `message:`?

**Comment by ResidentMario** [comment]
Renamed to `message`, but I can't reproduce this problem:

```
t4.Package().set("foo", "foo").build("foo/bar", message="foo")
with open("test.json", "w") as f:
    t4.Package.browse("foo/bar").dump(f)
!cat test.json

{"version": "v0", "message": "foo", "top_hash": {"alg": "v0", "value": "47d1c5b88296162a7fadb63ed31fe49ab1a994f0e97161772e4b73b6049f2933"}}
{"logical_key": "foo", "physical_keys": ["file:///Users/alex/Desktop/temp/foo"], "size": 0, "hash": {"type": "SHA256", "value": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}, "meta": {}}
```

```
p = t4.Package().set("foo", "foo")
p.build("foo/bar", message="foo")
with open("test.json", "w") as f:
    p.dump(f)
!cat test.json

{"version": "v0", "message": "foo", "top_hash": {"alg": "v0", "value": "47d1c5b88296162a7fadb63ed31fe49ab1a994f0e97161772e4b73b6049f2933"}}
{"logical_key": "foo", "physical_keys": ["file:///Users/alex/Desktop/temp/foo"], "size": 0, "hash": {"type": "SHA256", "value": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}, "meta": {}}
```

Both of these have a `message` populated.

**Comment by akarve** [comment]
I think we will want to merge this after #131; and revise it to store message in the dir-level metadata for `/`, package root?

**Comment by ResidentMario** [comment]
Well I was originally hoping to get this PR merged in first, but with the current state of affairs that's the correct course of action yeah.

**Comment by meffij** [comment]
@akarve @ResidentMario Top-level metadata is actually not impacted by dir-level metadata at all

**Comment by ResidentMario** [comment]
@meffij Looks like it does. Because the message goes to the top-level metadata it seems to mutate a component of the tophash, which is causing a test to fail because the tophash you get before you build (without a commit message) and the tophash you get after (with a tophash) is different.

**Comment by meffij** [comment]
That sounds correct, and that wouldn't be impacted by directory-level metadata. I was trying to say this PR does not depend on 131, because none of the stuff 131 does affects top-level metadata.

**Comment by stevededalus** [comment]
> I think we will want to merge this after #131; and revise it to store message in the dir-level metadata for `/`, package root?

Why have it on package root instead of top level?

**Comment by stevededalus** [comment]
This is a little strange, you're writing this as a commit message, but we have no notion of package history so it's really just a package description. The commit messages don't get append, the most recent wipes the old ones out. So if I modify two files in a set of 1,000 and commit with "Fix xyz.jpeg" that produces a package that just has message="Fix xyz.jpeg", that doesn't really mean anything.

**Comment by ResidentMario** [comment]
We discussed offline renaming the field to `description`. The point that there aren't truly meaningful versions is valid. After thinking about it for a time, I decided to keep it at `message` though, because `description` is an awkward argument for a `push` or `build` command. We can reinforce that it's really a per-version thing in our best practices.

**Pull request merged**
