### PR TITLE
Catalog: guest (anonymous) access to buckets

### PR DESCRIPTION
**Pull request by nl0**
Allow guest access to bucket browsing / search (using configurable guest credentials) if the bucket allows it.

To be merged after #164

### CODE REVIEW

**Comment by nl0** [comment]
rebased

**Comment by meffij** [comment]
Should `guestCredentials` be an optional entry in the config? @akarve do we have a sane default for guest credentials? Will most normal deployments have guest credentials?

**Comment by akarve** [comment]
We should skip guest credentials. Not only because it's questionable security, but also because we don't want to be trafficking key/secret pairs.

**Comment by akarve** [comment]
Withdrawing my objection. Guest credentials OK for now.

**Comment by meffij** [comment]
We do not intend to use this on any wide scale

We intend to switch to providing temporary credentials through a registry endpoint

Customers should not deploy this

**Pull request merged**
