### PR TITLE
Catalog: show code snippets as full-width expansion panels

### PR DESCRIPTION
**Pull request by nl0**

### CODE REVIEW

**Comment by nl0** [comment]
@akarve rtm, tho I'm not sure about the UI: 
image

**Comment by akarve** [comment]
hmm can you use this instead? (with text on left as well?) https://material-ui.com/demos/expansion-panels/#expansion-panels

**Comment by nl0** [comment]
@akarve with expansion panels:

image

image

**Comment by nl0** [comment]
#399

**Pull request closed without merging**
